config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
            passwords: "users/passwords",
            registrations: "users/registrations",
            omniauth_callbacks: "omniauth_callbacks"
          }
  devise_scope :user do 
    post "users/guest_sign_in", to: "users/sessions#new_guest"
  end

  root "books#top"

  resources :users,only: [:favorite] do 
    get "favorite", on: :collection
  end
  
  resources :books, only: [:index, :search] do
    get "search", on: :collection
  end

  resources :authors do 
    resource :author_favorites, only: [:index, :create, :destroy]
  end

  resources :favored_author_books

  resources :title_kanas do 
    resource :book_favorites, only: [:index, :create, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  attr_accessor :books 
  
  def top
    comics = RakutenWebService::Books::Book.search(
      booksGenreId: Genre.find_by(genre: "コミック").booksgenreid,
      sort: "sales",
      hits: 20
    )
    @unreleased_comics = comics.select{|book| book.sales_date.delete("/年|月|日|頃|/").gsub(/|上旬|中旬|下旬|以降/, "上旬" => "5", "中旬" => "15", "下旬" => "25", "以降" => "01").to_i > Time.current.strftime("%Y%m%d").to_i}
    
    light_novels = RakutenWebService::Books::Book.search(
      booksGenreId: Genre.find_by(genre: "ライトノベル").booksgenreid,
      sort: "sales",
      hits: 15
    )
    @unreleased_light_novels = light_novels.select{|book| book.sales_date.delete("/年|月|日|頃|/").gsub(/|上旬|中旬|下旬|以降/, "上旬" => "5", "中旬" => "15", "下旬" => "25", "以降" => "01").to_i > Time.current.strftime("%Y%m%d").to_i}

    novels_and_essays = RakutenWebService::Books::Book.search(
      booksGenreId: Genre.find_by(genre: "小説・エッセイ").booksgenreid,
      sort: "sales",
      hits: 15
    )
    @unreleased_novels_and_essays = novels_and_essays.select{|book| book.sales_date.delete("/年|月|日|頃| |　|/").gsub(/|上旬|中旬|下旬|以降/, "上旬" => "5", "中旬" => "15", "下旬" => "25", "以降" => "01").to_i > Time.current.strftime("%Y%m%d").to_i}
  end

  def search
    if params[:keyword].present?
      @author_books = RakutenWebService::Books::Book.search(
        author: params[:keyword],
        booksGenreId: params[:booksgenreid],
        orFlag: 0,
        sort: "sales",
      )
    else
      redirect_to root_path
    end
        
    if params[:keyword].present?
      @title_books = RakutenWebService::Books::Book.search(
        title: params[:keyword],
        booksGenreId: params[:booksgenreid],
        orFlag: 0,
        sort: "sales",
      )
    end
  end
end

app/views/books/_book_list.html.erb
<div class="col-4 col-md-3 col-lg-2 mb-4 p-0">
  <div class = "card border-secondary mb-3" style = "width:205px; border-width:2px;">
    <div class = "mx-auto card-header border-bottom p-0 m-0" style= "height: 200px;" >
        <%= link_to_if(book.large_image_url.present?, image_tag(book.large_image_url), book.item_url) %>
    </div>
    <div class="card-body book-body bg-secondary p-2" style= "height: 310px; color:#626262;">
      <div class = "favorite_button_container" >
        <p class = "favorite_button_item"><%= book.title %></p>
          <% if user_signed_in? %>
            <% title_kana = TitleKana.registered(book) %>
            <% if BookFavorite.favored_by?(title_kana, current_user) %>
              <%= render "title_kanas/favorite", title_kana: title_kana %>
            <% else %> 
              <%= render "title_kanas/not_favorite", title_kana: title_kana, book: book %>
            <% end %>
          <% else %>
            <%= render "title_kanas/not_favorite", title_kana: title_kana, book: book %>
          <% end %>
      </div>
      
      <div class = "favorite_button_container" >
        <p class = "favorite_button_item"><%= book.author %></p>
          <% if user_signed_in? %>
            <% author = Author.registered(book) %>
            <% if AuthorFavorite.favored_by?(author, current_user) %>
              <%= render "favorite", {author: author}%>
            <% else %> 
              <%= render "not_favorite", {author: author, book: book} %>
            <% end %>
          <% else %>
            <%= render "not_favorite", {author: author, book: book} %>
          <% end %>
      </div>

      <p class = "sales_date" ><%= book.sales_date %>発売</p>
      <p class = "item_price" ><%= book.item_price %>円(税込み)</p>
    </div>
  </div>
</div>

app/views/books/_favorite.html.erb
<%= form_with url: author_author_favorites_path(author_id: author.id), method: :delete, local: true do |f| %>
  <%= f.submit "この作者の新刊情報を受け取らない", class: "remove_from_favorite_button" %>
<% end %>

app/views/books/_not_favorite.html.erb
<% if user_signed_in? %>
  <%= form_with model: author, url: {controller: "authors", action: "create"}, method: :post, local: true do |f| %>
    <%= f.hidden_field :author_name, value: book.author.delete("/ |　/") %>
    <%= f.submit "この作者の新刊情報を通知",class: "favorite_button" %>
  <% end %>
<% else %>
  <%= form_with url: new_user_session_path, local: true do |f| %>
    <%= f.submit "この作者の新刊情報を通知",class: "favorite_button" %>
  <% end %>
<% end %>

app/views/books/_search_box.html.erb
<div class="search-box" style = "" >  
  <div class = "d-flex justify-content-center input-group my-3" >
    <%= form_with model:@book, url: search_books_path, method: :get, local: true do |f| %>
      <div class = "input-group-append" >
        <%= f.text_field :book, name: "keyword", placeholder: "作品名か作者名を入力してください", style: "width: 300px; border-width: 1px; border-color: #626262; padding: 2rem 1rem; border-top-left-radius: 0.25rem; border-bottom-left-radius: 0.25rem; height: 1rem; border-right: 0;" %>
        <%= f.collection_select :booksgenreid, Genre.all, :booksgenreid, :genre, {selected: "Genre.first"}, {class: " pl-2 pr-4", style: "border-width: 1px; border-color: #626262;"} %>
        <%= f.submit "検索",class: "text-white rounded-right", style: "border-width: 1px; border-color: #626262; background-color: #626262; padding:0 3rem;" %>
      </div>
    <% end %>
  </div>
</div>

app/views/books/_search_result.html.erb
<div class="col-4 col-md-3 col-lg-2 mb-4 p-0">
  <div class = "card border-secondary mb-3" style = "width:205px; border-width:2px;">
    <div class = "mx-auto card-header border-bottom p-0 m-0" style= "height: 200px;" >
        <%= link_to_if(book.large_image_url.present?, image_tag(book.large_image_url), book.item_url) %>
    </div>
    <div class="card-body book-body bg-secondary p-2" style= "height: 310px; color:#626262;">
      <div class = "favorite_button_container" >
        <p class = "favorite_button_item"><%= book.title %></p>
          <% if user_signed_in? %>
            <% title_kana = TitleKana.registered(book) %>
            <% if BookFavorite.favored_by?(title_kana, current_user) %>
              <%= render "title_kanas/favorite", title_kana: title_kana %>
            <% else %> 
              <%= render "title_kanas/not_favorite", title_kana: title_kana, book: book %>
            <% end %>
          <% else %>
            <%= render "title_kanas/not_favorite", title_kana: title_kana, book: book %>
          <% end %>
      </div>
      
      <div class = "favorite_button_container" >
        <p class = "favorite_button_item"><%= book.author %></p>
          <% if user_signed_in? %>
            <% author = Author.registered(book) %>
            <% if AuthorFavorite.favored_by?(author, current_user) %>
              <%= render "favorite", {author: author}%>
            <% else %> 
              <%= render "not_favorite", {author: author, book: book} %>
            <% end %>
          <% else %>
            <%= render "not_favorite", {author: author, book: book} %>
          <% end %>
      </div>

      <p><%= book.sales_date %>発売</p>
      <p><%= book.item_price %>円(税込み)</p>
    </div>
  </div>
</div>

app/views/books/_search_window.html.erb
<div id = "search-box">
    <%= form_with(url: search_books_path, method: :get, local: true) do |f| %>
      <%= f.text_field :book, id: "book_search", name: "keyword", placeholder: "キーワードを打ち込んで下さい", style: "width: 200px;" %>
      <%= submit_tag :"検索", name: :検索 %>
      <% end %>
</div>

app/views/books/_top_header_link.html.erb
<nav class="navbar navbar-expand px-0 pb-0">
  <%= link_to "ブクシル", root_path, class: "navbar-brand text-primary", id: "brand", style: "font-size:2rem;"%>
  <div class="navbar-nav">
    <% if user_signed_in? %>
    <!-- ログイン時 -->
      <%= link_to "お気に入り一覧", favorite_users_path, class: "nav-item nav-link text-primary" %>
      <%= link_to "アカウント編集", edit_user_registration_path, class: "nav-item nav-link text-primary" %>
      <%= link_to "ログアウト", destroy_user_session_path, class: "nav-item nav-link text-primary", method: :delete, data: { confirm: "ログアウトしますか？" } %>
    <% else %>
    <!-- 非ログイン時 -->
      <%= link_to "新規登録", new_user_registration_path, class: "nav-item nav-link text-primary" %>
      <%= link_to "ログイン", new_user_session_path, class: "nav-item nav-link text-primary" %>
      <%= link_to "ゲストログイン", users_guest_sign_in_path, class: "nav-item nav-link text-primary", method: :post %>
    <% end %>
  </div>
</nav>

app/views/books/home.html.erb
<h1>ブクシル</h1>
<p>好きな作家の新刊発売日が近くなるとメールでお知らせ</p>
<%= render "search_box" %>
<%= render "book_list", genre: Genre.find_by(genre: "コミック").genre, books: @unreleased_comics %>
<%= render "book_list", genre: Genre.find_by(genre: "ライトノベル").genre,books: @unreleased_light_novels %>
<%= render "book_list", genre: Genre.find_by(genre: "小説・エッセイ").genre,books: @unreleased_novels_and_essays %>

app/views/books/search.html.erb
<div class = "header-container">  
  <%= render "layouts/header_link" %>
  <%= render "search_box" %>
</div>

<%# お気に入り登録時のフラッシュメッセージ %>
<div class = "flash">
  <%= render "layouts/flash_register_favorite" %>
</div>

<div class = "content-wrapper">
  <div class = "container-fluid" >
    <div class = "row">
      <%= render partial: "search_result", collection: @title_books, as: "book" %>
      <%= render partial: "search_result", collection: @author_books, as: "book" %>
    </div>
  </div>
</div>

app/views/books/top.html.erb
<div class = "top-header-wrapper">
  <div class = "top-header-container">
    <%= render "layouts/header_link" %>
    <p class = "catch-copy" style = "margin-left:5%;">新刊の発売日3日前にメールでお知らせ</p>
    <%= render "search_box" %>
  </div>
</div>

<%# お気に入り登録時のフラッシュメッセージ %>
<div class = "flash">
  <%= render "layouts/flash_register_favorite" %>
</div>

<div class = "content-wrapper">
  <p class = "content-title">コミック</p>
  <div class = "container-fluid" >
    <div class = "row">
      <%= render partial: "book_list", collection: @unreleased_comics, as: "book" %>
    </div>
  </div>

  <p class = "content-title">小説・エッセイ</p>
  <div class = "container-fluid" >
    <div class = "row">
      <%= render partial: "book_list", collection: @unreleased_novels_and_essays, as: "book" %>
    </div>
  </div>

  <p class = "content-title">ライトノベル</p>
  <div class = "container-fluid" >
    <div class = "row">
      <%= render partial: "book_list", collection: @unreleased_light_novels, as: "book" %>
    </div>
  </div>
</div>